### ISSUE TITLE
Unrouted/Unconnected Item in Mosfet board - 

### ISSUE THREAD

**Issue by bantybanty** [KaeptnBalu/Arduino_Spot_Welder_V4#2]
Hi,

Firstly thank you for making the PCB and supported code.

Problem 1.
I am very new to Kicad. After opening the project and plotting Gerber files, I clicked Run DRC and found these items. Please verify the pads and their nets.
http://prntscr.com/15djesk

Problem 2. 
On JLPCB Website  "Can not identify the board outline"
https://prntscr.com/15dlfii

Siddharth

**Comment by KaeptnBalu** [comment]
Hi,
You need to do gerber files for both boards seperately. I do this by saving a copy of the Arduino_Spot_Welder_Kicad.pcb file as "Arduino_Board.pcb", then delete the mosfet board from it and then do the gerber creation. Do the same for the mosfet board. Also make sure when you order pcbs to get the mosfet board with at least 4 oz copper layer. A thinner copper layer will fail very quickly because of the high current.
